In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)

[1 2 3 4 5]


In [ ]:
#create 1 dimensional array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
a.shape

(5,)

In [ ]:
#2 dimensional array
b= np.array([(1,2,3,4),(2,3,5,6)])
print(b)
b.shape

[[1 2 3 4]
 [2 3 5 6]]


(2, 4)

In [ ]:
c= np.array([(1,2,3,4),(4,5,67,56),(12,34,56,56),(12,34,56,67)])
print(c)
print (type(c))
c.shape

[[ 1  2  3  4]
 [ 4  5 67 56]
 [12 34 56 56]
 [12 34 56 67]]
<class 'numpy.ndarray'>


(4, 4)

In [ ]:
# add float in list
a = np.array([(1,2,3,4,5),(2,3,5,6,6),(34,5,6,7,7),(23,4,56,7,88)],dtype =float)

print(a)
a.shape

[[ 1.  2.  3.  4.  5.]
 [ 2.  3.  5.  6.  6.]
 [34.  5.  6.  7.  7.]
 [23.  4. 56.  7. 88.]]


(4, 5)

In [ ]:
#numpy all array is zero
b= np.zeros((2,2))
print(b)

[[0. 0.]
 [0. 0.]]


In [ ]:
#numpy all array is ones
c= np.ones((3,4))
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# getting a particular value in array
c= np.full((2,3),4)
print(c)

[[4 4 4]
 [4 4 4]]


In [ ]:
#create array identity matrix using numpy
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# create array with random values
c = np.random.random((2,4))
print(c)

[[0.44333335 0.67378036 0.88413491 0.76720532]
 [0.09177845 0.32522088 0.37208069 0.74842835]]


In [ ]:
# random integer value within range
s = np.random.randint(10,20,(2,2))
print(s)

[[14 14]
 [12 15]]


In [ ]:
 #array of evenly spaced values ------ specifying the number of values required
e = np.linspace(20,50,15)
print(e)


[20.         22.14285714 24.28571429 26.42857143 28.57142857 30.71428571
 32.85714286 35.         37.14285714 39.28571429 41.42857143 43.57142857
 45.71428571 47.85714286 50.        ]


In [ ]:
 #array of evenly spaced values ------ specifying the number of steps required
e = np.arange(20,50,3)
print(e)


[20 23 26 29 32 35 38 41 44 47]


In [ ]:
list1 = [1,2,3,4,5]
np_array = np.asarray(list1)
print(np_array)
print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
list1 = (1,2,3,4,5)
np_array = np.asarray(list1)
print(np_array)
print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
a = np.random.randint(10,30,(2,2))
print(a)

[[16 18]
 [22 26]]


In [ ]:
print(a.ndim)

2


In [ ]:
print(a.size)

4


In [ ]:
list1 = [1,2,34,5]
list2 = [1,2,34,5]
add = list1 + list2
print(add)

[1, 2, 34, 5, 1, 2, 34, 5]


In [ ]:
list1 = [1,2,34,5]
list2 = [1,2,34,5]
print(np.add(list1,list2))

[ 2  4 68 10]


In [ ]:
print(np.multiply(list1,list2))

[   1    4 1156   25]


In [ ]:
a = np.random.randint(10,30,(3,2))
print(a)
print(a.shape)

[[17 28]
 [12 16]
 [15 20]]
(3, 2)


transpose

In [ ]:
b= np.transpose(a)
print(b)
print(b.shape)

[[17 12 15]
 [28 16 20]]
(2, 3)


In [ ]:
c = np.random.randint(10,30,(3,2))
print(c)
print(c.shape)

[[11 10]
 [27 26]
 [24 18]]
(3, 2)


In [ ]:
d = a.T
print(d)
print(d.shape)

[[17 12 15]
 [28 16 20]]
(2, 3)


In [ ]:
# reshape array
e= a.reshape(2,3)
print(e)
print(e.shape)

[[17 28 12]
 [16 15 20]]
(2, 3)
